server:
  port: 9000
spring:
  application:
    name: zuul-api-gateway
zuul:
  routes:
    ribbo-consumer:
      path: /ribbonapi/**
      serviceId: ribbo-consumer
    feign-consumer:
      path: /feignapi/**
      serviceId: feign-consumer

eureka:
 client:
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/
