server:
  port: 8781

eureka:
  instance:
    hostname: localhost
  server:
    renewal-percent-threshold: 0.7
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8781/eureka/

spring:
  application:
    name: eurka-server-8781